# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "@vagrant.basebox.name@"

  # Enable the Puppet provisioner
  config.vm.provision :puppet

  # Forward guest port 8080 to host port 4567
  config.vm.forward_port 8080, 4567
end
